name: TERRACARE ASSOCIATES
markdown: redcarpet
highlighter: true
baseurl: /terracare

exclude: ['node_modules', 'scss']

navigation:
- text: What we do
  url: /en/what-we-do/
- text: Who we are
  url: /en/who-we-are/
- text: Projects
  url: /en/projects/
  layout: project
- text: Blog
  url: /en/blog/
  layout: post
